"""Initial migration

Revision ID: 086c945424f7
Revises: 
Create Date: 2023-10-16 16:31:54.120908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086c945424f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('set_1_name', sa.String(), nullable=True),
    sa.Column('set_1_sets', sa.Integer(), nullable=True),
    sa.Column('set_1_reps', sa.Integer(), nullable=True),
    sa.Column('set_2_name', sa.String(), nullable=True),
    sa.Column('set_2_sets', sa.Integer(), nullable=True),
    sa.Column('set_2_reps', sa.Integer(), nullable=True),
    sa.Column('set_3_name', sa.String(), nullable=True),
    sa.Column('set_3_sets', sa.Integer(), nullable=True),
    sa.Column('set_3_reps', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workouts'))
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_posts_user_id_users')),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name=op.f('fk_posts_workout_id_workouts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('workouts')
    op.drop_table('users')
    # ### end Alembic commands ###
