"""empty message

Revision ID: 567b4ee0bd93
Revises: 086c945424f7
Create Date: 2023-10-16 16:33:21.259397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '567b4ee0bd93'
down_revision = '086c945424f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workout_posts_user_id_users')),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name=op.f('fk_workout_posts_workout_id_workouts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_posts'))
    )
    op.drop_table('posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('comments', sa.VARCHAR(), nullable=True),
    sa.Column('workout_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_posts_user_id_users'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name='fk_posts_workout_id_workouts'),
    sa.PrimaryKeyConstraint('id', name='pk_posts')
    )
    op.drop_table('workout_posts')
    # ### end Alembic commands ###
