"""Initial Migration

Revision ID: d6eee2f3ac47
Revises: 
Create Date: 2023-10-17 23:13:26.363092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6eee2f3ac47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('set_1_name', sa.String(), nullable=True),
    sa.Column('set_1_sets', sa.Integer(), nullable=True),
    sa.Column('set_1_reps', sa.Integer(), nullable=True),
    sa.Column('set_2_name', sa.String(), nullable=True),
    sa.Column('set_2_sets', sa.Integer(), nullable=True),
    sa.Column('set_2_reps', sa.Integer(), nullable=True),
    sa.Column('set_3_name', sa.String(), nullable=True),
    sa.Column('set_3_sets', sa.Integer(), nullable=True),
    sa.Column('set_3_reps', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workouts'))
    )
    op.create_table('workout_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workout_posts_user_id_users')),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name=op.f('fk_workout_posts_workout_id_workouts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_posts'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_posts')
    op.drop_table('workouts')
    op.drop_table('users')
    # ### end Alembic commands ###
